---
name: integration test
on: workflow_call
jobs:
  integration-test:
    permissions: {}
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod
      - run: |
          go install -ldflags "-X main.version=0.0.1-0 -X main.commit=$GITHUB_SHA -X main.date=$(date +"%Y-%m-%dT%H:%M:%SZ%:z" | tr -d '+')" ./cmd/ghaperf
      - run: ghaperf -v
      - run: ghaperf -h
      - run: ghaperf --log-file testdata/log.txt --threshold 1s
      - run: |
          run_id=$(gh run list -w test.yaml -s completed -L 1 --json databaseId -q ".[0].databaseId")
          ghaperf --repo "$GITHUB_REPOSITORY" --run-id "$run_id" --threshold 1s
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: |
          ghaperf --repo "$GITHUB_REPOSITORY" --workflow test.yaml --count 10 --threshold 1s
        env:
          GITHUB_TOKEN: ${{ github.token }}
